- name: Configure BYU BGP EVPN Automation
  hosts: all
  become: yes
  gather_facts: no
  
  tasks:
  
  - set_fact:
       poc-switch: "{{ hostvars[inventory_hostname] }}"

  - name: Deploy BGP and EVPN Address Familes
    nclu:
        commit: true
        description: "Deploy configuration"
        commands:
            - add loopback lo ip address {{ hostvars[inventory_hostname].loopback }}/32
            - add bgp autonomous-system {{ hostvars[inventory_hostname].bgpasn }}
            - add bgp network {{ hostvars[inventory_hostname].loopback }}/32
            - add bgp bestpath as-path multipath-relax
            - add bgp l2vpn evpn advertise-all-vni
            - add hostname {{ poc-switch.hostname }}
  
  - name: Deploy BGP and EVPN Interfaces
    nclu:
        commit: true
        description: "Deploy interfaces"
        commands:
            - add bgp neighbor swp"{{ item.int_name }}" remote-as "{{ item.type }}"
            - add bgp l2vpn evpn neighbor swp"{{ item.int_name }}" activate
    with_items:
      - "{{ hostvars[inventory_hostname].uplinks }}"
  
  - name: Reload Interfaces
    command: ifreload -a