- name: Configure BYU BGP EVPN Automation
  hosts: all
  become: yes
  gather_facts: no
  remote_user: cumulus

  tasks:
  
  - set_fact:
       poc_switch: "{{ hostvars[inventory_hostname] }}"

  - name: Deploy BGP and EVPN Address Familes
    nclu:
        commit: true
        description: "Deploy configuration"
        commands:
            - add loopback lo ip address {{ poc_switch.loopback }}/32
            - add interface eth0 vrf mgmt
            - add bgp autonomous-system {{ poc_switch.bgpasn }}
            - add bgp network {{ poc_switch.loopback }}/32
            - add bgp bestpath as-path multipath-relax
            - add bgp l2vpn evpn advertise-all-vni
            - add hostname {{ poc_switch.hostname }}
  
  - name: Deploy BGP and EVPN Interfaces
    nclu:
        commit: true
        description: "Deploy interfaces"
        commands:
            - add bgp neighbor swp"{{ item.int_name }}" remote-as "{{ item.type }}"
            - add bgp l2vpn evpn neighbor swp"{{ item.int_name }}" activate
    with_items:
      - "{{ poc_switch.uplinks }}"
  
  - name: Reload Interfaces
    command: ifreload -a