- name: Simple Debug Script
  hosts: all
  gather_facts: no
  
  tasks:
   - debug:
       msg: "{{ hostvars[inventory_hostname].loopback }}"

   - debug:
       msg: "{{ hostvars[inventory_hostname].uplinks }}"

   - debug:
       msg: "Uplinks: {{ item }}"
     with_items: "{{ hostvars[inventory_hostname].uplinks }}"
 
